baseurl = "https://ignisjang.netlify.app/"
title = "JANGc"
author = "Joe Hutchinson"
canonifyurls = true
paginate = 3
theme = "aether"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
brand = "JANGc"
description = "Blog of JYH"
bgimg = "img/bg_blue.jpg"
metaCreator = "Joe Hutchinson"
metaImage = "img/ogimage.jpg"

disqus_shortname = '{{ .Site.DisqusShortname }}'